(() => {
  'use strict';
  const Core=globalThis.NMDAImportCore, A=globalThis.NMDAImportAdapters;
  if(!Core||!A)throw new Error('Universal Import Engine 初始化失败：核心模块未加载。');

  const PROFILE_KEY='nmda.import.profiles.v1';
  const detector=new A.FormatDetector();
  const DIRECT_ATTACHMENT_EXT=new Set(['pdf','ppt','pptx','rtf','png','jpg','jpeg','gif','webp','svg','zip','rar','7z']);

  const SOURCE_PURPOSES={mail:'mail',roster:'roster',attachment:'attachment',ignored:'ignored',ambiguous:'ambiguous'};
  const ROSTER_HEADER_PATTERNS={
    email:/^(?:邮箱|邮箱地址|导师邮箱|教授邮箱|联系邮箱|email|emailaddress|mail|contactemail)$/i,
    name:/^(?:导师|导师姓名|教授|教授姓名|姓名|老师|联系人|supervisor|professor|faculty|name|contactname)$/i,
    school:/^(?:学校|院校|大学|高校|所属学校|所属院校|机构|单位|university|school|institution|organisation|organization|affiliation)$/i,
    workflow:/^(?:批次|轮次|第几批|联系批次|发送批次|状态|联系状态|套磁状态|申请状态|优先级|排序|等级|分类|标签|分组|方向|备注|batch|round|wave|status|contactstatus|priority|rank|tier|tag|tags|category|group|notes?|remarks?)$/i
  };
  const MATERIAL_NAME_RE=/(?:^|[^a-z])(?:cv|resume)(?:[^a-z]|$)|curriculum\s+vitae|transcript|research\s+proposal|writing\s+sample|personal\s+statement|简历|履历|成绩单|研究计划|个人陈述|写作样本/i;
  const MATERIAL_TEXT_CUES=[/curriculum\s+vitae|\bresume\b|个人简历|学术简历/i,/education|academic\s+background|教育经历|教育背景/i,/work\s+experience|employment|工作经历/i,/research\s+experience|科研经历/i,/publications?|论文发表|代表性论文/i,/skills?|awards?|honou?rs?|技能|获奖/i,/transcript|成绩单/i,/research\s+proposal|研究计划/i];

  function formatLocalDateTime(date){if(!(date instanceof Date)||Number.isNaN(date.getTime()))return'';const p=n=>String(n).padStart(2,'0');return`${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}T${p(date.getHours())}:${p(date.getMinutes())}`;}
  function parseDateValue(value){return Core.parseDateLoose(value);}

  function validPurpose(value){return Object.values(SOURCE_PURPOSES).includes(String(value||''))?String(value):'';}
  function recordSetText(recordSet,limit=24000){return (recordSet?.rows||[]).slice(0,160).flatMap(row=>row||[]).map(v=>String(v??'')).join('\n').slice(0,limit);}
  function explicitMailFields(detection){
    const out=new Set();
    for(const [field,evidence] of Object.entries(detection?.evidence||{}))if(String(evidence).includes('header')&&Number(detection?.confidence?.[field]||0)>=70)out.add(field);
    return out;
  }
  function rosterHeaderEvidence(headers){
    const found=new Set();
    for(const raw of headers||[]){const header=Core.normalizeHeader(raw);for(const [field,re] of Object.entries(ROSTER_HEADER_PATTERNS))if(re.test(header))found.add(field);}
    return found;
  }
  function classifyRecordSet(recordSet,{forcedPurpose=''}={}){
    const meta=recordSet?.meta||{},forced=validPurpose(forcedPurpose||meta.purposeOverride);
    if(forced)return{purpose:forced,confidence:100,reasons:['来源已明确指定用途']};
    if(meta.supplemental)return{purpose:SOURCE_PURPOSES.ignored,confidence:100,reasons:['已有更可靠的邮件识别结果，原始结构仅作解析依据']};
    if(meta.mailFrames)return{purpose:SOURCE_PURPOSES.mail,confidence:Math.max(92,Number(meta.mailScan?.averageConfidence||0)),reasons:['识别到邮件称呼、主题、正文或落款边界']};

    const detection=Core.detectHeader(recordSet?.rows||[]),mailFields=explicitMailFields(detection),headers=detection.headers||[];
    const hasRecipient=mailFields.has('recipients'),hasSubject=mailFields.has('subject'),hasBody=mailFields.has('body');
    const sourceName=`${recordSet?.source||''} ${recordSet?.name||''}`,text=recordSetText(recordSet);
    const materialName=MATERIAL_NAME_RE.test(sourceName),materialCues=MATERIAL_TEXT_CUES.filter(re=>re.test(text)).length;
    if(materialName||(meta.wordTaskRows&&meta.kind==='records'&&materialCues>=3))return{purpose:SOURCE_PURPOSES.attachment,confidence:materialName&&materialCues?98:materialName?94:88,reasons:[materialName?'文件名符合 CV/简历/申请材料':'',materialCues?`内容包含 ${materialCues} 类简历或申请材料线索`:''].filter(Boolean)};
    // oneFileTask is a fallback envelope generated by the Word adapter. Its standard
    // columns are not source-authored mail headers and therefore cannot prove mail intent.
    if(meta.oneFileTask){
      if(materialName||materialCues>=2)return{purpose:SOURCE_PURPOSES.attachment,confidence:materialName&&materialCues?98:materialName?94:88,reasons:[materialName?'文件名符合 CV/简历/申请材料':'',materialCues?`内容包含 ${materialCues} 类简历或申请材料线索`:''].filter(Boolean)};
      return{purpose:SOURCE_PURPOSES.ambiguous,confidence:45,reasons:['仅检测到普通文档正文，没有足够邮件结构证据']};
    }
    if((hasRecipient&&(hasSubject||hasBody))||(hasSubject&&hasBody)){
      return{purpose:SOURCE_PURPOSES.mail,confidence:hasRecipient&&hasSubject&&hasBody?98:91,reasons:[`表头明确包含${[hasRecipient?'收件人':'',hasSubject?'主题':'',hasBody?'正文':''].filter(Boolean).join('、')}`]};
    }

    const rosterFields=rosterHeaderEvidence(headers),identityCount=['email','name','school'].filter(key=>rosterFields.has(key)).length;
    if(identityCount>=2&&!hasSubject&&!hasBody){
      return{purpose:SOURCE_PURPOSES.roster,confidence:rosterFields.has('workflow')?97:93,reasons:[`表头包含${[rosterFields.has('name')?'姓名':'',rosterFields.has('email')?'邮箱':'',rosterFields.has('school')?'院校':'',rosterFields.has('workflow')?'批次/状态':''].filter(Boolean).join('、')}，且没有邮件主题/正文`]};
    }

    if(!hasRecipient&&!hasSubject&&!hasBody&&(materialName||(meta.oneFileTask&&materialCues>=2))){
      return{purpose:SOURCE_PURPOSES.attachment,confidence:materialName&&materialCues?98:materialName?94:88,reasons:[materialName?'文件名符合 CV/简历/申请材料':'',materialCues?`内容包含 ${materialCues} 类简历或申请材料线索`:''].filter(Boolean)};
    }

    if(identityCount>=1&&!hasSubject&&!hasBody)return{purpose:SOURCE_PURPOSES.ambiguous,confidence:55,reasons:['可能是联系人资料，但不足以自动作为总名单']};
    return{purpose:SOURCE_PURPOSES.ambiguous,confidence:35,reasons:['未找到足够的邮件、名单或附件结构证据']};
  }

  function annotateRecordSet(recordSet,options={}){
    const result=classifyRecordSet(recordSet,options);
    recordSet.meta={...(recordSet.meta||{}),sourcePurpose:result.purpose,purposeConfidence:result.confidence,purposeReasons:result.reasons};
    return result;
  }
  function recordSetSources(recordSet){const members=recordSet?.meta?.sourceMembers;return members?.length?[...members]:[recordSet?.source||recordSet?.name||'未命名来源'];}
  function summarizeSourceRouting(recordSets,sourceFiles=[]){
    const bySource=new Map();
    const touch=name=>{const key=String(name||'未命名来源');if(!bySource.has(key))bySource.set(key,{source:key,purposes:{mail:0,roster:0,attachment:0,ignored:0,ambiguous:0},recordSets:0,reasons:[]});return bySource.get(key);};
    for(const file of sourceFiles||[])touch(file?._nmdaPath||file?.webkitRelativePath||file?.name);
    for(const rs of recordSets||[])for(const source of recordSetSources(rs)){const item=touch(source),purpose=validPurpose(rs.meta?.sourcePurpose)||SOURCE_PURPOSES.ambiguous;item.purposes[purpose]++;item.recordSets++;item.reasons.push(...(rs.meta?.purposeReasons||[]));}
    return[...bySource.values()].map(item=>({...item,reasons:[...new Set(item.reasons)].slice(0,4)}));
  }
  function prepareDataset(dataset){
    const sets=dataset?.recordSets||dataset?.sheets||[];
    for(const rs of sets)annotateRecordSet(rs);
    const routing=summarizeSourceRouting(sets,dataset?.sourceFiles||[]),attachmentSources=new Set(routing.filter(item=>item.purposes.attachment>0&&!item.purposes.mail&&!item.purposes.roster).map(item=>item.source));
    const routedAttachments=(dataset?.sourceFiles||[]).filter(file=>attachmentSources.has(String(file?._nmdaPath||file?.webkitRelativePath||file?.name||'')));
    dataset.meta={...(dataset.meta||{}),sourceRouting:routing};
    dataset.routedFiles={...(dataset.routedFiles||{}),attachments:routedAttachments};
    return dataset;
  }
  function directAttachmentFile(file){return DIRECT_ATTACHMENT_EXT.has(A.extOf(file?.name))&&A.extOf(file?.name)!=='zip';}
  function attachmentRecordSet(file){return new Core.NormalizedRecordSet({name:`附件候选 · ${file?.name||'未命名文件'}`,rows:[['文件名','用途'],[file?.name||'','附件候选']],source:file?.name||'',meta:{kind:'asset',purposeOverride:SOURCE_PURPOSES.attachment}});}
  function unreadableRecordSet(file,error){return new Core.NormalizedRecordSet({name:`暂不使用 · ${file?.name||'未命名文件'}`,rows:[['文件名','读取结果'],[file?.name||'',error?.message||'无法读取']],source:file?.name||'',meta:{kind:'unreadable',purposeOverride:SOURCE_PURPOSES.ignored}});}


  function mergeWordTaskRecordSets(recordSets,{namePrefix='Word文档批次',source='multi-word',packageMode=false}={}){
    const candidates=(recordSets||[]).filter(rs=>rs.meta?.wordTaskRows && rs.meta?.sourcePurpose===SOURCE_PURPOSES.mail && !rs.meta?.supplemental);
    if(candidates.length<2)return false;
    const header=['编号','收件人','学校 / 机构','主题','正文','附件','定时时间','任务标记','来源文件'],rows=[header],rowMeta={};
    let mailFrameCount=0, confidenceTotal=0, confidenceCount=0, scanBlocks=0, scanSubjects=0, scanSalutations=0, scanClosings=0, scanEmails=0;
    for(const rs of candidates){
      const d=Core.detectHeader(rs.rows||[]);
      for(let rowIndex=d.index+1;rowIndex<(rs.rows||[]).length;rowIndex++){
        const row=rs.rows[rowIndex]; if(!row?.some(v=>String(v??'').trim()))continue;
        rows.push(header.map((_,i)=>row[i]??''));
        const meta=rs.meta?.rowMeta?.[rowIndex]; if(meta)rowMeta[rows.length-1]={...meta};
      }
      if(rs.meta?.mailFrames){
        mailFrameCount++;
        const scan=rs.meta?.mailScan||{};scanBlocks+=Number(scan.blocks||0);scanSubjects+=Number(scan.subjects||0);scanSalutations+=Number(scan.salutations||0);scanClosings+=Number(scan.closings||0);scanEmails+=Number(scan.emails||0);
        for(const meta of Object.values(rs.meta?.rowMeta||{})){if(Number(meta?.confidence)>0){confidenceTotal+=Number(meta.confidence);confidenceCount++;}}
      }
    }
    for(let i=recordSets.length-1;i>=0;i--)if(candidates.includes(recordSets[i]))recordSets.splice(i,1);
    const dataRows=rows.slice(1), mailScan=mailFrameCount?{blocks:scanBlocks,subjects:scanSubjects,salutations:scanSalutations,closings:scanClosings,emails:scanEmails,records:dataRows.length,complete:dataRows.filter(r=>String(r[1]||'').trim()&&String(r[2]||'').trim()&&String(r[3]||'').trim()).length,missingRecipients:dataRows.filter(r=>!String(r[1]||'').trim()).length,averageConfidence:confidenceCount?Math.round(confidenceTotal/confidenceCount):0}:null;
    recordSets.unshift(new Core.NormalizedRecordSet({name:`${namePrefix}（${rows.length-1} 条）`,rows,source,meta:{word:true,merged:true,wordTaskRows:true,preferred:true,package:packageMode,mailFrames:mailFrameCount>0,rowMeta,sourcePurpose:SOURCE_PURPOSES.mail,purposeConfidence:96,purposeReasons:['仅合并已确认为邮件的 Word 来源'],sourceMembers:[...new Set(candidates.flatMap(recordSetSources))],...(mailScan?{mailScan}: {})}}));
    return true;
  }

  class UniversalImportEngine{
    constructor({registry=A.registry, detectorInstance=detector}={}){this.registry=registry;this.detector=detectorInstance;}

    async parseFile(file,{allowZipBatch=true}={}){
      if(!file)throw new Error('没有选择导入文件。');
      const buffer=await file.arrayBuffer(), detection=await this.detector.detect(file,buffer);
      if(detection.format==='xls')throw new Error('已识别为旧版 Excel .xls（OLE/BIFF）。当前通用引擎尚未启用二进制 XLS Adapter；请另存为 XLSX/ODS/CSV。');
      if(detection.format==='doc')throw new Error('已识别为旧版 Word .doc（二进制 OLE）。WordAdapter 当前支持 DOCX/DOCM/DOTX；请在 Word/WPS 中另存为 .docx 后批量导入。');
      if(detection.format==='zip'){
        if(!allowZipBatch)throw new Error('ZIP 内再次嵌套 ZIP 暂不支持。');
        return this.parseZipBatch(file,buffer,detection.entries||await A.unzip(buffer));
      }
      const adapter=this.registry.find(detection.format) || this.registry.find(detection.container==='text'?'text':detection.format);
      if(!adapter)throw new Error(`已识别格式“${detection.format}”，但当前没有对应 Adapter。`);
      const result=await adapter.parse({file,buffer,detection,engine:this});
      result.meta={...(result.meta||{}), detection, adapter:adapter.name};
      return prepareDataset(result);
    }

    async parseFiles(files,{ignoreUnsupported=false}={}){
      const list=[...(files||[])].filter(Boolean);if(!list.length)throw new Error('没有选择数据文件。');
      const recordSets=[],sourceFiles=[],embeddedFiles=[],warnings=[],formats=[];
      for(const file of list){
        if(directAttachmentFile(file)){sourceFiles.push(file);formats.push('attachment');recordSets.push(attachmentRecordSet(file));continue;}
        try{
          const ds=await this.parseFile(file); formats.push(ds.format); sourceFiles.push(...(ds.sourceFiles||[file])); embeddedFiles.push(...(ds.embeddedFiles||[])); warnings.push(...(ds.warnings||[]));
          for(const rs of ds.sheets||[]){const prefix=list.length>1?`${file.name} · `:'';recordSets.push(new Core.NormalizedRecordSet({name:`${prefix}${rs.name}`,rows:rs.rows,source:file.name,meta:{...(rs.meta||{}),format:ds.format}}));}
        }catch(error){
          if(MATERIAL_NAME_RE.test(String(file?.name||''))){sourceFiles.push(file);formats.push('attachment');recordSets.push(attachmentRecordSet(file));warnings.push(`${file.name}: 无法解析文档内容，已保守放入附件候选（${error.message}）`);continue;}
          if(ignoreUnsupported||list.length>1){sourceFiles.push(file);formats.push('unreadable');recordSets.push(unreadableRecordSet(file,error));warnings.push(`${file.name}: 读取失败，已隔离为“暂不使用”，不影响其他来源（${error.message}）`);continue;}throw error;
        }
      }
      // 多个“一文件一封”/字段式 Word/邮件原语集合自动合并，并保留逐条识别证据。
      if(list.length>1)mergeWordTaskRecordSets(recordSets,{source:'multi-word'});
      if(!recordSets.length)throw new Error(warnings.length?`没有成功读取的数据文件。${warnings[0]}`:'没有可读取的数据。');
      return prepareDataset(new Core.NormalizedDataset({format:[...new Set(formats)].join('+')||'multi',recordSets,sourceFiles,embeddedFiles,warnings,meta:{multiFile:list.length>1}}));
    }

    async parseDirectory(files){
      const candidates=[...(files||[])].filter(file=>A.candidateDataFile(file)||directAttachmentFile(file));if(!candidates.length)throw new Error('所选目录中没有支持的邮件资料或附件。');
      return this.parseFiles(candidates,{ignoreUnsupported:true});
    }

    async parseZipBatch(zipFile,buffer,entries){
      const warnings=[],embeddedFiles=[];let manifest=null;
      const manifestBytes=entries.get('manifest.json')||entries.get('nmda-manifest.json');
      if(manifestBytes){try{manifest=JSON.parse(A.decodeText(manifestBytes));}catch(e){throw new Error(`ZIP manifest.json 无法解析：${e.message}`);}}
      const names=[...entries.keys()].filter(n=>n&&!n.endsWith('/')&&!n.startsWith('__MACOSX/'));
      let taskNames=[];
      if(manifest?.taskFile){const exact=String(manifest.taskFile).replace(/^\.\//,'');if(!entries.has(exact))throw new Error(`ZIP manifest 指定的任务文件不存在：${exact}`);taskNames=[exact];}
      else taskNames=names.filter(n=>A.SUPPORTED_EXT.has(A.extOf(n))&&A.extOf(n)!=='zip'&&!/^manifest\.json$/i.test(n));
      if(!taskNames.length)throw new Error('ZIP 中没有找到任务数据文件。建议包含 manifest.json + tasks.xlsx/csv/json/docx。');
      const recordSets=[],sourceFiles=[];
      for(const name of taskNames){const bytes=entries.get(name),vf=A.makeVirtualFile(name,bytes);try{const ds=await this.parseFile(vf,{allowZipBatch:false});sourceFiles.push(vf);for(const rs of ds.sheets)recordSets.push(new Core.NormalizedRecordSet({name:`${name} · ${rs.name}`,rows:rs.rows,source:name,meta:{...(rs.meta||{}),package:true,format:ds.format}}));}catch(e){warnings.push(`${name}: ${e.message}`);}}
      mergeWordTaskRecordSets(recordSets,{source:zipFile.name,packageMode:true});
      const taskSet=new Set(taskNames);
      const attachmentRoot=String(manifest?.attachmentRoot||'').replace(/^\.\//,'').replace(/\/+$/,'');
      for(const name of names){if(taskSet.has(name)||/^manifest\.json$/i.test(name))continue;if(attachmentRoot&&!(name===attachmentRoot||name.startsWith(`${attachmentRoot}/`)))continue;embeddedFiles.push(A.makeVirtualFile(name,entries.get(name)));}
      if(!recordSets.length)throw new Error(`ZIP 中的任务文件均解析失败：${warnings[0]||'未知原因'}`);
      return prepareDataset(new Core.NormalizedDataset({format:'nmda-zip',recordSets,sourceFiles:[zipFile,...sourceFiles],embeddedFiles,warnings,meta:{manifest,package:true}}));
    }
  }

  const engine=new UniversalImportEngine();

  async function parseFile(file){return engine.parseFile(file);}
  async function parseFiles(files){return engine.parseFiles(files);}
  async function parseDirectory(files){return engine.parseDirectory(files);}

  function createProfile({name='',format='',collectionName='',sheetName='',headers=[],mapping={},confidence={}}={}){
    const sourceCollection = collectionName || sheetName || '';
    return {id:`profile_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,name:name||`导入模板 ${new Date().toLocaleDateString()}`,format,collectionName:sourceCollection,sheetName:sourceCollection,headers:[...headers],normalizedHeaders:headers.map(Core.normalizeHeader),mapping:{...mapping},confidence:{...confidence},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
  }
  function loadProfiles(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'[]').filter(x=>x&&x.id);}catch(_){return[];}}
  function saveProfile(profile){const all=loadProfiles(),i=all.findIndex(x=>x.id===profile.id),next={...profile,updatedAt:new Date().toISOString()};if(i>=0)all[i]=next;else all.push(next);localStorage.setItem(PROFILE_KEY,JSON.stringify(all.slice(-50)));return next;}
  function deleteProfile(id){const all=loadProfiles().filter(x=>x.id!==id);localStorage.setItem(PROFILE_KEY,JSON.stringify(all));}
  function suggestProfile({format='',headers=[]}={}){const target={format,headers};return loadProfiles().map(p=>({profile:p,score:Core.profileSimilarity(p,target)})).sort((a,b)=>b.score-a.score)[0]||null;}

  function splitAttachments(value){return String(value??'').split(/[;；|\n]+/).map(v=>v.trim()).filter(Boolean);}
  function normalizeFileKey(value){return String(value??'').normalize('NFKC').trim().replace(/\\/g,'/').replace(/^\.\//,'').replace(/^\/+/, '').replace(/\/{2,}/g,'/').toLowerCase();}
  function baseName(value){const key=normalizeFileKey(value);return key.split('/').filter(Boolean).pop()||'';}
  function relaxedFileName(value){const name=baseName(value),dot=name.lastIndexOf('.'),stem=dot>0?name.slice(0,dot):name,ext=dot>0?name.slice(dot):'';return`${stem.replace(/\s*[（(]\d+[）)]\s*$/,'').trim()}${ext}`;}
  function filePath(file){return file?.webkitRelativePath||file?._nmdaPath||file?.name||'';}
  function fileIdentity(file){return`${normalizeFileKey(filePath(file))}|${Number(file?.size||0)}|${Number(file?.lastModified||0)}`;}
  function addIndex(map,key,file){if(!key)return;if(!map.has(key))map.set(key,[]);const list=map.get(key);if(!list.some(x=>fileIdentity(x)===fileIdentity(file)))list.push(file);}
  function buildFileIndex(files){const exact=new Map(),byName=new Map(),relaxedByName=new Map(),unique=new Map();for(const file of files||[]){if(!file)continue;unique.set(fileIdentity(file),file);const relative=normalizeFileKey(filePath(file)),withoutRoot=relative.includes('/')?relative.split('/').slice(1).join('/'):'';for(const path of [file.name,relative,withoutRoot].filter(Boolean).map(normalizeFileKey))addIndex(exact,path,file);const name=baseName(file.name);addIndex(byName,name,file);addIndex(relaxedByName,relaxedFileName(name),file);}return{exact,byName,relaxedByName,files:[...unique.values()]};}
  function resolveOneFile(ref,index){const key=normalizeFileKey(ref);if(!key)return{ref,status:'missing',candidates:[],method:'empty'};let matches=index?.exact?.get(key)||[];if(matches.length===1)return{ref,status:'matched',file:matches[0],candidates:matches,method:'exact'};if(matches.length>1)return{ref,status:'ambiguous',candidates:matches,method:'exact'};const basename=baseName(key);matches=index?.byName?.get(basename)||[];if(matches.length===1)return{ref,status:'matched',file:matches[0],candidates:matches,method:'basename'};if(matches.length>1)return{ref,status:'ambiguous',candidates:matches,method:'basename'};const relaxed=relaxedFileName(basename);matches=index?.relaxedByName?.get(relaxed)||[];if(matches.length===1)return{ref,status:'matched',file:matches[0],candidates:matches,method:'relaxed-copy-suffix'};if(matches.length>1)return{ref,status:'ambiguous',candidates:matches,method:'relaxed-copy-suffix'};return{ref,status:'missing',candidates:[],method:'none'};}
  function candidateScore(ref,file){const w=baseName(ref),a=baseName(file?.name);if(!w||!a)return 0;if(w===a)return 100;if(relaxedFileName(w)===relaxedFileName(a))return 90;const ws=w.replace(/\.[^.]+$/,''),as=a.replace(/\.[^.]+$/,'');if(ws&&as&&(ws.includes(as)||as.includes(ws)))return 65;const t=new Set(ws.split(/[^\p{L}\p{N}]+/u).filter(x=>x.length>1)),o=new Set(as.split(/[^\p{L}\p{N}]+/u).filter(x=>x.length>1));let overlap=0;for(const x of t)if(o.has(x))overlap++;return overlap?30+Math.min(30,overlap*10):0;}
  function suggestFiles(ref,index,limit=12){return[...(index?.files||[])].map(file=>({file,score:candidateScore(ref,file)})).sort((a,b)=>b.score-a.score||String(a.file.name).localeCompare(String(b.file.name))).slice(0,Math.max(1,limit));}
  function resolveFiles(refs,index){const files=[],missing=[],ambiguous=[],details=[];for(const ref of refs||[]){const d=resolveOneFile(ref,index||buildFileIndex([]));details.push(d);if(d.status==='matched')files.push(d.file);else if(d.status==='missing')missing.push(ref);else ambiguous.push(ref);}return{files,missing,ambiguous,details};}

  globalThis.NMDAImporter={
    version:'1.24.0', engine, UniversalImportEngine,
    FIELD_DEFS:Core.FIELD_DEFS, normalizeHeader:Core.normalizeHeader, mappingForHeaders:Core.mappingForHeaders,
    detectHeader:Core.detectHeader, detectBestSheet:Core.detectBestSheet, detectBestRecordSet:Core.detectBestRecordSet, parseFile, parseFiles, parseDirectory,
    parseDateValue,formatLocalDateTime,createProfile,loadProfiles,saveProfile,deleteProfile,suggestProfile,
    splitAttachments,normalizeFileKey,relaxedFileName,fileIdentity,buildFileIndex,resolveOneFile,suggestFiles,resolveFiles,
    supportedFormats:['XLSX','ODS','FODS','DOCX/DOCM/DOTX','CSV','TSV','PSV','TXT','JSON','JSONL/NDJSON','HTML table','Excel 2003 XML','ZIP batch'],
    candidateDataFile:A.candidateDataFile,directAttachmentFile,
    SOURCE_PURPOSES,classifyRecordSet,annotateRecordSet,summarizeSourceRouting,prepareDataset,mergeWordTaskRecordSets
  };
})();
